### ISSUE TITLE
Review of the recommendedState:"" per category

### ISSUE THREAD

**Issue by apapageorgiou** [joomla-projects/cookiescript#1]

**Comment by Alcaeusd** [comment]
Based on the outcome of the discussion in Glip, a 2nd branch "forceScriptChanges" has been created, in order to modify the whole view of the script (to prevent syntax malfunction). Also, as for recommendedState, it is set to true and lawfulBasis:'legitimate interest' has been commited for future review. Also, recommendedState has been removed from Advertising Cookies Category as it is not needed there for the moment.

**Comment by jeckodevelopment** [comment]
merged with https://github.com/joomla-projects/cookiescript/pull/2
